

services:
  db-service:
    image: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    networks:
      - back

  nest-app:
    build: ./back-end
    image: uni-api
    networks:
      - back
    depends_on:
      - db-service

  db-client:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root              
      ME_CONFIG_MONGODB_PORT: 27017 
      ME_CONFIG_MONGODB_SERVER: db-service
    ports:
      - 8081:8081
    networks:
      - back
    depends_on:
      - db-service


networks:
  back: {}

