version: "2.4"
name: ssr
services:
  db-service:
    image: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    networks:
      back:
        ipv4_address: 172.30.0.2

  nest-app:
    build: ./back-end
    image: test-repo:uni-api
    networks:
      back:
        ipv4_address: 172.30.0.3
    depends_on:
      - db-service

  db-client:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}              
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT} 
      ME_CONFIG_MONGODB_SERVER: db-service
    ports:
      - ${DB_CLIENT_EXPOSED_PORT}:8081
    networks:
      back:
        ipv4_address: 172.30.0.4
    depends_on:
      - db-service

  ang-app:
    build: ./Front-end 
    image: test-repo:uni-front
    networks:
      back:
        ipv4_address: 172.30.0.5
    ports:
      - ${FRONT_END_EXPOSED_PORT}:4000
    depends_on:
      - nest-app

networks:
  back:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.30.0.0/24
          gateway: 172.30.0.1

