# syntax=docker/dockerfile:1
FROM node:18-alpine3.18

RUN mkdir uni-api 

WORKDIR /uni-api 

COPY package* /uni-api/

RUN npm i 

COPY . /uni-api/

RUN npm run build

EXPOSE 3000

CMD npm run start:prod




