name: build-deploy-prod


on:
  push:
    branches:
      - master
    pull_request:
      - master
  
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking out your repo
        uses: actions/checkout@v4

      - name: test stage
        run: echo "hi, is running"

      - name: build docker images
        run: docker compose build

  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: log in to docker hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: tag images before push
        run: |
          docker tag test-repo:uni-front amrhossam/test-repo:uni-front
          docker tag test-repo:uni-api amrhossam/test-repo:uni-api

      - name: pushing images to docker hub 
        run: |
          docker push amrhossam/test-repo:uni-front
          docker push amrhossam/test-repo:uni-api