name: build-deploy-prod


on:
  push:
    branches:
      - master
    pull_request:
      - master
  
jobs:
  build-job:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checking out your repo
        uses: actions/checkout@v4

      - name: test stage
        run: echo "hi, is running"

      - name: prepare env. vars files for front app
        run: |
          cd Front-end/src/environments/
          rm prod.env.ts
          
          echo "export const env = {" >> prod.env.ts
          echo "baseURL: '${{secrets.BASE_URL}}'," >> prod.env.ts
          echo "apiURL: '${{secrets.API_URL}}'" >> prod.env.ts
          echo "}" >> prod.env.ts

      - name: build docker images
        run: docker compose build

      - name: saving image as tar
        run: | 
          docker save -o front-image.tar test-repo:uni-front
          docker save -o api-image.tar test-repo:uni-api
      
      - name: save the front image artifiact
        uses: actions/upload-artifact@v4
        with:
          name: front-image
          path: ./front-image.tar
          retention-days: 1
          overwrite: true

      - name: save the api image artifiact
        uses: actions/upload-artifact@v4
        with:
          name: api-image
          path: ./api-image.tar
          retention-days: 1
          overwrite: true


  push-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: log in to docker hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 


      - name: download front image artifact
        uses: actions/download-artifact@v4
        with:
          name: front-image
          path: .


      - name: download api image artifact
        uses: actions/download-artifact@v4
        with:
          name: api-image
          path: .

      - name: inspect inside files
        run: |
          ls -R

      - name: loading images into docker
        run: |
          docker load -i front-image.tar
          docker load -i api-image.tar

      - name: tag images before push
        run: |
          docker tag test-repo:uni-front amrhossam/test-repo:uni-front
          docker tag test-repo:uni-api amrhossam/test-repo:uni-api

      - name: pushing images to docker hub 
        run: |
          docker push amrhossam/test-repo:uni-front
          docker push amrhossam/test-repo:uni-api

  
  deploy-job:
    needs: push-job
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checking out your repo
        uses: actions/checkout@v4

      - name: login to dockerhub
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_HOST }}   
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p "${{secrets.DOCKER_PASSWORD}}"

      - name: pulling images from dockerhub
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_HOST }}   
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker pull amrhossam/test-repo:uni-front
            sudo docker pull amrhossam/test-repo:uni-api
      
      - name: export prod env secrets as a file
        run: |
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" > .env
          ehco "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} >> .env
          ehco "MONGO_PORT=${{ secrets.MONGO_PORT }} >> .env
          ehco "FRONT_END_EXPOSED_PORT=${{ secrets.FRONT_END_EXPOSED_PORT }} >> .env
          ehco "API_EXPOSED_PORT=${{ secrets.API_EXPOSED_PORT }} >> .env
          ehco "DB_CLIENT_EXPOSED_PORT=${{ secrets.DB_CLIENT_EXPOSED_PORT }} >> .env


      - name: copying compose and env files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          overwrite: true
          source: compose.yaml,.env
          target: ~/uni-app

      - name: kill running containers
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_HOST }}   
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/uni-app/
            sudo docker compose down

      - name: relaunch containers
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_HOST }}   
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/uni-app
            sudo docker tag amrhossam/test-repo:uni-front test-repo:uni-front
            sudo docker tag amrhossam/test-repo:uni-api test-repo:uni-api
            sudo docker compose up -d
